version: "3.4"
x-hydra:
  &default-hydra
  build:
    context: ../../docker/
  shm_size: '2gb'
  environment:

services:
  subscriber:
    <<: *default-hydra
    environment:
      ENTRY_POINT: "com.weareadaptive.hydra.training.aeron.Subscriber"
      JVM_ARGS: "-Dchannel=aeron:udp?endpoint=subscriber:9000"

  publisher:
    << : *default-hydra
    environment:
      ENTRY_POINT: "com.weareadaptive.hydra.training.aeron.Publisher"
      JVM_ARGS: "-Dchannel=aeron:udp?endpoint=subscriber:9000"